language: python
sudo: required

python:
  - "3.5"

services:
  - docker

git:
  depth: 3

install:
  - docker pull fedora
  - pip install -U coveralls

script:
  - >
    docker run -t -v ${PWD}:${PWD}:Z fedora /bin/sh -c
    "dnf install -y python3-{numpy,scipy,pillow,matplotlib,cycler,h5py,root,tox};
    cd ${PWD};
    tox -epy35;"

after_script:
    - coveralls
